import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      sidebar: {
        allGames: "All My Games", forYou: "For You", analytics: "Analytics", friends: "Friends", gameNights: "Game Nights", personalLists: "Personal Lists", friendGroups: "Friend Groups", createNewGroup: "Create New Group", appTools: "App Tools", copyExport: "Copy Export Data", importClipboard: "Import from Clipboard", signOut: "Sign Out"
      },
      search: {
        title: "Add to Library", placeholder: "Search for a game...", button: "Search", emptyState: "Search for a game to add it to your collection.", noImage: "No Image", players: "Players", mins: "Mins", addTooltip: "Add Game", error: "Error searching for games.", alreadyInLibrary: "{{name}} is already in your library!", addSuccess: "{{name}} added to your library!", addFailed: "Failed to add game."
      },
      gameCard: {
        notOwner: "Not Owner", deleteLibrary: "Delete from Library", removeGroup: "Remove from Group", noImage: "No Image", unknownYear: "Unknown Year", players: "Players", mins: "Mins", logScore: "Log Score", assignLists: "Assign Lists", sharedByFriend: "Shared by friend", expansions: "Expansions"
      },
      home: {
        allMyGames: "All My Games", gameCount: "{{count}} games", cancelBulk: "Cancel Bulk", assign: "Assign", bulkEdit: "Bulk Edit", invite: "Invite", addFromLibrary: "Add from Library", searchNewGame: "Search New Game", searchNew: "Search New", filtersSorting: "Filters & Sorting", filterByName: "Filter by name...", players: "Players", recentlyAdded: "Recently Added", alphabetical: "Alphabetical", releaseYear: "Release Year", whatToPlay: "What to Play?", noMatchesFilter: "No games match your current filters.", confirmDeleteLibrary: "Delete \"{{name}}\" from your collection?", confirmRemoveList: "Remove \"{{name}}\" from this list?", deleted: "Deleted!", removed: "Removed!", copied: "Copied to clipboard!", emptyClipboard: "Empty clipboard.", imported: "Imported!", invalidJson: "Invalid JSON.", enterGroupName: "Enter a name for your new friend group:", created: "Created!", failed: "Failed.", confirmDeleteGroup: "Delete \"{{name}}\"?", noMatches: "No matches!", signIn: "Sign in with Google"
      },
      scores: {
        logMatch: "Log Match", historyTab: "History ({{count}})", competitive: "Competitive", coop: "Co-op Mode", victory: "Victory", defeat: "Defeat", playersInvolved: "Players Involved", playerScores: "Player Scores", playerName: "Player Name", scoreMath: "Score Math", eq: "Eq:", addPlayer: "Add Player Row", attachPhoto: "Attach Memory Photo", noMatches: "No recorded matches found.", loggedBy: "Logged by {{name}}", coopVictory: "Co-op Victory", coopDefeat: "Co-op Defeat", pts: "pts", close: "Close", syncing: "Syncing...", saveMatch: "Save Match Log"
      },
      gameDetails: {
        title: "Game Details", noImage: "No Image", players: "Players", community: "Community", best: "Best", playingTime: "Playing Time", min: "Min", sleeveGuide: "BGG Sleeve Guide", setCost: "Set Game Cost", roi: "ROI", perPlay: "/ play", pubDesc: "Publisher Description", editTrans: "Edit Translation", addThai: "Add Thai Description", fetching: "Fetching latest BGG data...", cancel: "Cancel", saveTrans: "Save Translation", matchHistory: "Match History ({{count}})", noHistory: "No recorded matches yet. Log a score to see history here!", justNow: "Just now", loggedBy: "Logged by {{name}}", pts: "pts", thaiPlaceholder: "Type or paste Thai description here...",
        rulesAndVideos: "Rules & Video Tutorials", englishGuide: "English Guide", bggVideoHub: "BoardGameGeek Video Hub", bggVideoDesc: "Browse official community instructions, setup layouts, and full rules breakdowns on BGG.", openBggVideos: "Open BGG Videos →", thaiGuide: "Thai Guide", youtubeSearch: "Search Thai Tutorials on YouTube", youtubeDesc: "Find detailed Thai language instructional videos from top creators like BGN, Lanlalen, and Roll Your Dice.", openYoutube: "Search YouTube →"
      },
      analytics: {
        scaleMsg: "Shelf snapshot loaded! Tap 2 points across a standard Credit Card width.", boundsMsg: "Scale set! Now drag/tap a rectangle box bounding your empty shelf gap area.", libCap: "Library Capitalization", netVal: "Net Value / Play", sessions: "{{count}} sessions", camTitle: "Camera Vision Space Analyzer", camDesc: "Take a photo of any empty space or customized shelf slot to analyze your physical packing configuration dynamically.", snapBtn: "Snapshot Shelf or Closet Space", step1: "✨ Step 1: Tap the two width ends of a credit card to calibrate scale context.", step2: "📐 Step 2: Tap the top-left, then bottom-right corner of your empty space.", step3: "✅ Matrix compiled successfully!", targetDim: "Analyzed Target Dimensions", calcW: "Calculated Width", calcH: "Calculated Height", resetCam: "Reset Camera View", geoPlan: "Geometric Storage Blueprint Plan", calibReq: "Calibrate the canvas frame image step markers above to compute placement sequences.", tooTight: "Space constraints are too tight to support your library layout components. Optimize dimensions!", roiChamp: "ROI Champions (Best Value)", playsCount: "{{count}} plays", neverPlayed: "Never played", perPlay: "per play", shelfSitters: "Shelf Sitters (Needs Play)", hallOfFame: "Hall of Fame (Wins)", winsCount: "{{count}} Wins", placeFlat: "Place Flat in Row layer", stackSecond: "Stack securely on second tier"
      },
      friends: {
        noMatch: "No account matching that email address was found.", noSelf: "You cannot link to yourself.", alreadyLinked: "This user is already linked to another partner account.", linkSuccess: "Successfully linked accounts! Your libraries are now merged.", linkFail: "Failed to link partner accounts.", unlinkConfirm: "Are you sure you want to unlink your shared library from your partner?", unlinkSuccess: "Accounts successfully unlinked.", unlinkFail: "Failed to unlink accounts.", addNoFind: "No account found.", addNoSelf: "You cannot add yourself.", followed: "Followed {{name}}!", addFail: "Failed to add friend.", removeConfirm: "Stop following {{name}}'s library?", removed: "Removed {{name}}.", removeFail: "Failed to remove friend.", coupleTitle: "Couple Shared Library", coupleDesc: "Link your account with your partner's. Friends will view both of your games combined as a single shared household library.", linkedPartner: "Linked Partner", partnerEmail: "Partner's email address...", linkBtn: "Link Partner", followTitle: "Follow Friend Collections", followDesc: "Input your game group friend's registration email to track their shelf contents.", followBtn: "Follow Link", myCircle: "My Gaming Circle ({{count}})", emptyCircle: "Your circle roster is currently empty. Follow friends above!", coupledShelf: "Coupled Shelf", viewShelf: "View Shelf", removeFriend: "Remove Friend", returnRoster: "← Return to Friend Roster", browsing: "Browsing {{name}}'s Library", searchFriend: "Search friend's games...", noMatching: "No matching titles discovered on this friend's collection framework.", weight: "Weight", expansion: "Expansion"
      },
      gameNights: {
        maxPropose: "You can only propose up to 10 games.", minPropose: "Please propose at least 1 game!", createSuccess: "Game night created! Share the link for guests.", createFail: "Failed to create event.", rsvpYes: "You're in! Vote for up to 5 games below.", rsvpUpdated: "RSVP updated.", rsvpFail: "Failed to update RSVP.", maxVote: "You can only vote for up to 5 games.", voteFail: "Failed to submit vote.", copySuccess: "Guest link copied! Send it in your group chat.", cancelConfirm: "Cancel this game night for everyone?", cancelSuccess: "Event canceled.", cancelFail: "Failed to cancel event.", hubTitle: "Game Night Hub", hubDesc: "Plan sessions, collect RSVPs, and multi-vote on what hits the table.", hostBtn: "Host Game Night", planTitle: "Plan a Session", eventTitle: "Event Title", titlePlace: "e.g. Friday Night Dice", date: "Date", timeLoc: "Time & Location (Optional)", locPlace: "7:00 PM @ My Place", proposeCount: "Propose Games ({{count}}/10)", searchLib: "Search your library...", createBtn: "Create Event", noUpcoming: "No upcoming game nights.", cancelEvent: "Cancel Event", playersGoing: "{{count}} players going", copyGuest: "Copy Guest Link", yourRsvp: "Your RSVP", imIn: "I'm In", out: "Out", voteTitle: "Vote for up to 5 games", voteCount: "{{count}}/5 Votes", rsvpUnlock: "RSVP \"I'm In\" to unlock voting!", upTo: "Up to {{count}} players"
      },
      recommendations: {
        unavailable: "Unavailable.", failed: "Failed.", added: "Added!", analyzing: "Analyzing your library...", smartDisc: "Smart Discover", matchesFor: "Matches for", players: "players", and: "and", mins: "mins", unknownYear: "Unknown Year", addToLib: "Add to Library"
      },
      common: { loading: "Dusting off your shelf...", cancel: "Cancel", save: "Save" }
    }
  },
  th: {
    translation: {
      sidebar: {
        allGames: "เกมทั้งหมดของฉัน", forYou: "สำหรับคุณ", analytics: "สถิติ", friends: "เพื่อน", gameNights: "นัดเล่นเกม", personalLists: "รายการส่วนตัว", friendGroups: "กลุ่มเพื่อน", createNewGroup: "สร้างกลุ่มใหม่", appTools: "เครื่องมือ", copyExport: "คัดลอกข้อมูล", importClipboard: "นำเข้าข้อมูล", signOut: "ออกจากระบบ"
      },
      search: {
        title: "เพิ่มลงในคลัง", placeholder: "ค้นหาเกม...", button: "ค้นหา", emptyState: "ค้นหาเกมเพื่อเพิ่มลงในคอลเล็กชันของคุณ", noImage: "ไม่มีรูปภาพ", players: "ผู้เล่น", mins: "นาที", addTooltip: "เพิ่มเกม", error: "เกิดข้อผิดพลาดในการค้นหาเกม", alreadyInLibrary: "คุณมี {{name}} ในคลังอยู่แล้ว!", addSuccess: "เพิ่ม {{name}} ลงในคลังสำเร็จ!", addFailed: "เพิ่มเกมไม่สำเร็จ"
      },
      gameCard: {
        notOwner: "ไม่ใช่เจ้าของ", deleteLibrary: "ลบออกจากคลัง", removeGroup: "ลบออกจากกลุ่ม", noImage: "ไม่มีรูปภาพ", unknownYear: "ไม่ระบุปี", players: "ผู้เล่น", mins: "นาที", logScore: "บันทึกคะแนน", assignLists: "จัดการรายการ", sharedByFriend: "แบ่งปันโดยเพื่อน", expansions: "ภาคเสริม"
      },
      home: {
        allMyGames: "เกมทั้งหมดของฉัน", gameCount: "{{count}} เกม", cancelBulk: "ยกเลิกแก้ไข", assign: "จัดการ", bulkEdit: "แก้ไขหลายรายการ", invite: "เชิญ", addFromLibrary: "เพิ่มจากคลัง", searchNewGame: "ค้นหาเกมใหม่", searchNew: "ค้นหาใหม่", filtersSorting: "ตัวกรองและการเรียงลำดับ", filterByName: "กรองตามชื่อ...", players: "ผู้เล่น", recentlyAdded: "เพิ่มล่าสุด", alphabetical: "ตามตัวอักษร", releaseYear: "ปีที่วางจำหน่าย", whatToPlay: "เล่นอะไรดี?", noMatchesFilter: "ไม่มีเกมที่ตรงกับตัวกรองของคุณ", confirmDeleteLibrary: "ลบ \"{{name}}\" ออกจากคอลเล็กชันของคุณหรือไม่?", confirmRemoveList: "ลบ \"{{name}}\" ออกจากรายการนี้หรือไม่?", deleted: "ลบแล้ว!", removed: "นำออกแล้ว!", copied: "คัดลอกไปยังคลิปบอร์ดแล้ว!", emptyClipboard: "คลิปบอร์ดว่างเปล่า", imported: "นำเข้าสำเร็จ!", invalidJson: "JSON ไม่ถูกต้อง", enterGroupName: "ป้อนชื่อสำหรับกลุ่มเพื่อนใหม่ของคุณ:", created: "สร้างสำเร็จ!", failed: "ล้มเหลว", confirmDeleteGroup: "ลบ \"{{name}}\" หรือไม่?", noMatches: "ไม่พบข้อมูล!", signIn: "เข้าสู่ระบบด้วย Google"
      },
      scores: {
        logMatch: "บันทึกแมตช์", historyTab: "ประวัติ ({{count}})", competitive: "แข่งขัน", coop: "โหมดร่วมมือ", victory: "ชนะ", defeat: "พ่ายแพ้", playersInvolved: "ผู้เล่นที่เข้าร่วม", playerScores: "คะแนนผู้เล่น", playerName: "ชื่อผู้เล่น", scoreMath: "คำนวณคะแนน", eq: "สมการ:", addPlayer: "เพิ่มผู้เล่น", attachPhoto: "แนบรูปภาพ", noMatches: "ไม่พบประวัติการเล่น", loggedBy: "บันทึกโดย {{name}}", coopVictory: "ชนะ (Co-op)", coopDefeat: "พ่ายแพ้ (Co-op)", pts: "แต้ม", close: "ปิด", syncing: "กำลังซิงค์...", saveMatch: "บันทึกข้อมูล"
      },
      gameDetails: {
        title: "รายละเอียดเกม", noImage: "ไม่มีรูปภาพ", players: "ผู้เล่น", community: "ผู้เล่นทั่วไป", best: "ดีที่สุด", playingTime: "เวลาเล่น", min: "นาที", sleeveGuide: "คู่มือซองการ์ด BGG", setCost: "ตั้งค่าราคาเกม", roi: "ความคุ้มค่า", perPlay: "/ รอบ", pubDesc: "คำอธิบายจากผู้จัดพิมพ์", editTrans: "แก้ไขคำแปล", addThai: "เพิ่มคำอธิบายภาษาไทย", fetching: "กำลังดึงข้อมูลล่าสุดจาก BGG...", cancel: "ยกเลิก", saveTrans: "บันทึกคำแปล", matchHistory: "ประวัติการเล่น ({{count}})", noHistory: "ยังไม่มีประวัติการเล่น บันทึกคะแนนเพื่อดูประวัติที่นี่!", justNow: "เมื่อสักครู่", loggedBy: "บันทึกโดย {{name}}", pts: "แต้ม", thaiPlaceholder: "พิมพ์หรือวางคำอธิบายภาษาไทยที่นี่...",
        rulesAndVideos: "วิธีเล่น & วิดีโอแนะนำ", englishGuide: "คู่มือภาษาอังกฤษ", bggVideoHub: "ศูนย์รวมวิดีโอ BoardGameGeek", bggVideoDesc: "ค้นหาวิดีโอสอนเล่น วิธีการเซ็ตอัป และการอธิบายกฎกติกาอย่างละเอียดจากชุมชน BGG", openBggVideos: "เปิดวิดีโอ BGG →", thaiGuide: "คู่มือภาษาไทย", youtubeSearch: "ค้นหาวิธีเล่นบน YouTube", youtubeDesc: "ค้นหาวิดีโอสอนเล่นภาษาไทยอย่างละเอียดจากแคสเตอร์ชั้นนำ เช่น BGN, Lanlalen และ Roll Your Dice", openYoutube: "ค้นหาบน YouTube →"
      },
      analytics: {
        scaleMsg: "โหลดรูปภาพชั้นวางแล้ว! แตะ 2 จุดให้เท่ากับความกว้างของบัตรเครดิต", boundsMsg: "ตั้งค่าสัดส่วนแล้ว! ลากหรือแตะเพื่อสร้างกรอบสี่เหลี่ยมในช่องว่างบนชั้นวาง", libCap: "มูลค่าคลังเกม", netVal: "ความคุ้มค่าต่อรอบ", sessions: "{{count}} รอบ", camTitle: "วิเคราะห์พื้นที่จัดเก็บด้วยกล้อง", camDesc: "ถ่ายภาพช่องว่างบนชั้นวางของคุณเพื่อคำนวณพื้นที่จัดเก็บเกมที่เหมาะสมที่สุด", snapBtn: "ถ่ายภาพชั้นวางหรือพื้นที่ว่าง", step1: "✨ ขั้นตอนที่ 1: แตะขอบซ้ายขวาของบัตรเครดิตในภาพเพื่อวัดสัดส่วน", step2: "📐 ขั้นตอนที่ 2: แตะมุมซ้ายบนและขวาล่างของพื้นที่ว่าง", step3: "✅ คำนวณพื้นที่สำเร็จ!", targetDim: "ขนาดพื้นที่ที่วิเคราะห์", calcW: "ความกว้างที่คำนวณได้", calcH: "ความสูงที่คำนวณได้", resetCam: "ตั้งค่ากล้องใหม่", geoPlan: "แผนผังการจัดเก็บเกม", calibReq: "ปรับเทียบกรอบรูปภาพด้านบนเพื่อคำนวณลำดับการจัดวาง", tooTight: "พื้นที่แคบเกินไปสำหรับเกมในคลังของคุณ กรุณาปรับขนาดใหม่!", roiChamp: "คุ้มค่าที่สุด (บาท/รอบ)", playsCount: "เล่น {{count}} รอบ", neverPlayed: "ยังไม่เคยเล่น", perPlay: "ต่อรอบ", shelfSitters: "เกมนอนกล่อง (ควรหยิบมาเล่น)", hallOfFame: "หอเกียรติยศ (ชนะมากที่สุด)", winsCount: "ชนะ {{count}} ครั้ง", placeFlat: "วางแนวนอน", stackSecond: "ซ้อนชั้นที่สอง"
      },
      friends: {
        noMatch: "ไม่พบบัญชีที่ตรงกับอีเมลนี้", noSelf: "คุณไม่สามารถเชื่อมโยงบัญชีกับตัวเองได้", alreadyLinked: "ผู้ใช้นี้เชื่อมโยงกับบัญชีอื่นแล้ว", linkSuccess: "เชื่อมโยงบัญชีสำเร็จ! รวมคลังเกมของคุณแล้ว", linkFail: "เชื่อมโยงบัญชีไม่สำเร็จ", unlinkConfirm: "คุณแน่ใจหรือไม่ว่าต้องการยกเลิกการเชื่อมโยงคลังเกมกับคู่ของคุณ?", unlinkSuccess: "ยกเลิกการเชื่อมโยงบัญชีสำเร็จ", unlinkFail: "ยกเลิกการเชื่อมโยงบัญชีไม่สำเร็จ", addNoFind: "ไม่พบบัญชี", addNoSelf: "คุณไม่สามารถเพิ่มตัวเองเป็นเพื่อนได้", followed: "ติดตาม {{name}} แล้ว!", addFail: "เพิ่มเพื่อนไม่สำเร็จ", removeConfirm: "เลิกติดตามคลังเกมของ {{name}} หรือไม่?", removed: "ลบ {{name}} แล้ว", removeFail: "ลบเพื่อนไม่สำเร็จ", coupleTitle: "คลังเกมแบบคู่รัก", coupleDesc: "เชื่อมบัญชีของคุณกับคู่รัก เพื่อนๆ จะเห็นเกมของพวกคุณรวมกันเป็นคลังเดียว", linkedPartner: "บัญชีคู่รักที่เชื่อมไว้", partnerEmail: "อีเมลของคู่รัก...", linkBtn: "เชื่อมโยงคู่รัก", followTitle: "ติดตามคลังเกมของเพื่อน", followDesc: "ใส่อีเมลที่เพื่อนใช้ลงทะเบียนเพื่อติดตามเกมบนชั้นวางของพวกเขา", followBtn: "ติดตามบัญชี", myCircle: "กลุ่มเพื่อนเล่นเกม ({{count}})", emptyCircle: "กลุ่มเพื่อนของคุณว่างเปล่า ติดตามเพื่อนด้านบนเลย!", coupledShelf: "คลังเกมคู่รัก", viewShelf: "ดูชั้นวาง", removeFriend: "ลบเพื่อน", returnRoster: "← กลับไปหน้ารายชื่อเพื่อน", browsing: "กำลังดูคลังเกมของ {{name}}", searchFriend: "ค้นหาเกมของเพื่อน...", noMatching: "ไม่พบเกมที่ตรงกันในคลังของเพื่อน", weight: "ความยาก", expansion: "ภาคเสริม"
      },
      gameNights: {
        maxPropose: "คุณเสนอเกมได้สูงสุด 10 เกม", minPropose: "กรุณาเสนออย่างน้อย 1 เกม!", createSuccess: "สร้างนัดเล่นเกมสำเร็จ! แชร์ลิงก์ให้แขกของคุณเลย", createFail: "สร้างกิจกรรมไม่สำเร็จ", rsvpYes: "เข้าร่วมแล้ว! โหวตเกมที่คุณอยากเล่นได้สูงสุด 5 เกม", rsvpUpdated: "อัปเดตการตอบรับแล้ว", rsvpFail: "อัปเดตการตอบรับไม่สำเร็จ", maxVote: "คุณโหวตได้สูงสุด 5 เกม", voteFail: "บันทึกผลโหวตไม่สำเร็จ", copySuccess: "คัดลอกลิงก์แขกแล้ว! ส่งในแชทกลุ่มได้เลย", cancelConfirm: "ยกเลิกนัดเล่นเกมนี้สำหรับทุกคนหรือไม่?", cancelSuccess: "ยกเลิกกิจกรรมแล้ว", cancelFail: "ยกเลิกกิจกรรมไม่สำเร็จ", hubTitle: "ศูนย์รวมนัดเล่นเกม", hubDesc: "วางแผนนัดหมาย เก็บคำตอบรับ และโหวตเกมที่จะลงโต๊ะ", hostBtn: "สร้างนัดเล่นเกม", planTitle: "วางแผนรอบเล่นเกม", eventTitle: "ชื่อกิจกรรม", titlePlace: "เช่น นัดทอยเต๋าคืนวันศุกร์", date: "วันที่", timeLoc: "เวลาและสถานที่ (ระบุหรือไม่ก็ได้)", locPlace: "19:00 น. ที่บ้านของฉัน", proposeCount: "เสนอเกม ({{count}}/10)", searchLib: "ค้นหาคลังเกมของคุณ...", createBtn: "สร้างกิจกรรม", noUpcoming: "ไม่มีนัดเล่นเกมที่กำลังจะมาถึง", cancelEvent: "ยกเลิกกิจกรรม", playersGoing: "ผู้เล่นตอบรับเข้าร่วม {{count}} คน", copyGuest: "คัดลอกลิงก์แขก", yourRsvp: "การตอบรับของคุณ", imIn: "ฉันเข้าร่วม", out: "ไม่เข้าร่วม", voteTitle: "โหวตเกมได้สูงสุด 5 เกม", voteCount: "โหวตแล้ว {{count}}/5 เกม", rsvpUnlock: "ตอบรับ \"ฉันเข้าร่วม\" เพื่อปลดล็อกการโหวต!", upTo: "เล่นได้ถึง {{count}} คน"
      },
      recommendations: {
        unavailable: "ไม่พร้อมใช้งาน", failed: "ล้มเหลว", added: "เพิ่มแล้ว!", analyzing: "กำลังวิเคราะห์คลังเกมของคุณ...", smartDisc: "ค้นหาเกมอัจฉริยะ", matchesFor: "เหมาะสำหรับผู้เล่น", players: "คน", and: "และเวลาประมาณ", mins: "นาที", unknownYear: "ไม่ระบุปี", addToLib: "เพิ่มลงในคลัง"
      },
      common: { loading: "กำลังปัดฝุ่นชั้นวางเกม...", cancel: "ยกเลิก", save: "บันทึก" }
    }
  }
};

i18n.use(LanguageDetector).use(initReactI18next).init({ resources, fallbackLng: 'en', interpolation: { escapeValue: false } });

export default i18n;